### ISSUE TITLE
Generate text file does not supports UTF-8

### ISSUE THREAD

**Issue by emanjon** [ietf-tools/ietf-at-ui#105] opened 2022-08-03 11:04 UTC
Generate HTML supports UTF-8. Generate text file does not supports UTF-8. My name is generated as "Preu&#258;&#159; Mattsson". I feel discriminated. Why is anything else than UTF-8 even allowed?

John Preuß Mattsson

![](https://memegenerator.net/img/instances/34003190.jpg)

**Comment by kesara** [comment] 2022-08-03 11:32
@emanjon Can you provide an example draft?

**Comment by kesara** [comment] 2022-08-03 11:45
There was a similar issue in #14 where that seems to be the browser is trying to use the wrong charset.

Did you try to open the text document from a different editor?

Also, what's the browser/editor that you are using?

**Comment by emanjon** [comment] 2022-08-03 12:03
Thank for the quick response. Yes, this seems very similar to #14. It does depend on the browser used. 

The official xml for RFC 9190 is a good example (i.e., it does not depend on my editor).
https://www.rfc-editor.org/rfc/rfc9190.xml

- The compilation to text **does not** produce the correct non-ASCII characters when using Safari Version 15.6 (17613.3.9.1.5) on MacOS Montery Version 12.5.
- The compilation to html **does** produce the correct non-ASCII characters when using Safari Version 15.6 (17613.3.9.1.5) on MacOS Montery Version 12.5.
- The compilation to text and html **does** produce the correct non-ASCII characters when using Firefox 103.0 (64-bit) on MacOS Montery Version 12.5.

So the problem is either in the Safari browser or the code for https://author-tools.ietf.org.

**Comment by kesara** [comment] 2022-08-03 12:31
Thanks for the information. I can reproduce the issue in Safari 15.6.
It turns out that the default encoding in Safari is `Windows (ISO Latin 1)`.
If you change the default encoding to `Unicode (UTF-8)` text displays fine.

You can change this from "Preferences -> Advanced":
<img width="791" alt="Screen Shot 2022-08-04 at 12 25 57 AM" src="https://user-images.githubusercontent.com/1027692/182607712-1280ac25-dd41-45b3-a78d-fa08291cc3fd.png">

I'll investigate if there's anything more that I could do from author tools side to make this work better on Safari.

**Comment by emanjon** [comment] 2022-08-03 12:36
Thanks!

> default encoding in Safari is Windows (ISO Latin 1)

🤦‍♀️

> I'll investigate if there's anything more that I could do from author tools side to make this work better on Safari.

As generating HTML with Safari works without changing the default encoding I would expect that it is possible to make it work better.

**Comment by kesara** [comment] 2022-08-03 23:14
>As generating HTML with Safari works without changing the default encoding I would expect that it is possible to make it work better.

It is easier with HTML because `charset` can be defined in `meta`.

**Comment by kesara** [comment] 2024-01-10 21:03
Closing this issue as this repository is being archived.
Report new issues and feature requests to https://github.com/ietf-tools/ietf-at

**Closed by kesara** 2024-01-10 21:03 UTC
