### ISSUE TITLE
vspace doesn't work for a v2 file

### ISSUE THREAD

**Issue by brtech99** [ietf-tools/ietf-at-ui#57] opened 2021-11-29 18:49 UTC
If run the version of xml2rfc on tools.ietf.org, a v2 file with VSPACE , it works.  If I run it on author-tools, it doesn't (it ignores the VSPACE).   

The rfc part is:
<?rfc toc="yes"?>
<?rfc symrefs="yes" ?>
<?rfc sortrefs="yes"?>
<?rfc iprnotified="no" ?>
<?rfc strict="no" ?>

<rfc category="std" ipr="trust200902" docName="draft-ietf-ecrit-similar-location-14"
    updates="5222">

The VSPACE text:
<t>Input address:
<vspace/>6000 15th Avenue
<vspace/>Leets, WA US
</t>

I worked around this by changing to:
<t>Input address:
<ul empty="true" spacing="compact">
<li>6000 15th Avenue</li>
<li>Leets, WA US</li></ul>
</t>

**Comment by kesara** [comment] 2024-01-10 20:51
Apologies for the late reply.
Author tools convert v2 drafts to v3.
Maybe this is the cause of the issue.
This repository is being archived so I'm closing this issue.
New repository for author tools is https://github.com/ietf-tools/ietf-at

**Closed by kesara** 2024-01-10 20:51 UTC
